### ISSUE TITLE
updated for newer jQuery?

### ISSUE THREAD

**Issue by judodan** [flesler/jquery.preload#6]
I am updating my website and I like this preloader. Any chance there's a version that works with jQuery 3.4+ ?

When I activate the preload, it gets an error here:

        var imgs = $(Array(settings.threshold+1).join('<img/>'))
            .load(handler).on('error',handler).bind('abort',handler).each(fetch);

the error is:
jQuery.Deferred exception: e.indexOf is not a function TypeError: e.indexOf is not a function
    at k.fn.init.k.fn.load (https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js:2:83689)
....

**Comment by flesler** [comment]
Hi, sadly there isn't (yet). Pull requests are accepted

**Comment by judodan** [comment]
I did a local fix (which works), then when I went back to the code, I noticed the fix was already there, but there just hasn't been an update to the releases page.

**Comment by flesler** [comment]
Oh you are right. I pushed the code, published to NPM but didn't tag or release on Github. Just did, thanks!
